// Searchable emoji library: [emoji, "space-separated keywords"]
// Star is first so it's the default/top pick.
export const EMOJI_DATA = [
  ["⭐", "star favorite"],
  ["🌟", "star glowing sparkle"],
  ["✨", "sparkles magic clean"],
  ["✅", "check done complete yes"],
  ["🔥", "fire hot streak urgent"],
  ["🎯", "target goal bullseye dart"],
  ["📌", "pin location important"],
  ["📍", "pin map location"],
  ["📅", "calendar date schedule"],
  ["🗓️", "calendar date schedule"],
  ["⏰", "alarm clock time"],
  ["⏳", "hourglass time waiting"],
  ["💪", "muscle strong gym workout fitness"],
  ["🏃", "run running exercise jog"],
  ["🚴", "bike cycling bicycle exercise"],
  ["🏋️", "weights lifting gym workout"],
  ["🧘", "yoga meditate zen calm"],
  ["🏊", "swim swimming pool"],
  ["⚽", "soccer football sports ball"],
  ["🏀", "basketball sports ball"],
  ["🏈", "football sports ball"],
  ["⚾", "baseball sports ball"],
  ["🎾", "tennis sports ball"],
  ["🏐", "volleyball sports ball"],
  ["🥊", "boxing gloves fight"],
  ["⛳", "golf flag sports"],
  ["🎿", "ski skiing snow winter"],
  ["🛹", "skateboard skate"],
  ["📚", "books reading study school"],
  ["📖", "book reading open"],
  ["📓", "notebook journal notes"],
  ["✏️", "pencil write edit"],
  ["🖊️", "pen write"],
  ["📝", "memo note writing list"],
  ["💻", "laptop computer work code"],
  ["🖥️", "desktop computer monitor"],
  ["⌨️", "keyboard typing"],
  ["🖱️", "mouse computer"],
  ["📱", "phone mobile smartphone"],
  ["☎️", "telephone phone call"],
  ["📞", "phone call receiver"],
  ["📧", "email mail message"],
  ["✉️", "envelope mail letter"],
  ["📦", "package box shipping delivery"],
  ["🏠", "house home"],
  ["🏡", "house home garden"],
  ["🏢", "office building work"],
  ["🏥", "hospital medical health"],
  ["🏦", "bank money finance"],
  ["🏫", "school education"],
  ["⛪", "church religion"],
  ["🏛️", "government museum classical"],
  ["🚗", "car auto vehicle drive"],
  ["🚙", "suv car vehicle"],
  ["🚕", "taxi cab car"],
  ["🚌", "bus transit"],
  ["🚂", "train locomotive"],
  ["✈️", "airplane flight travel trip"],
  ["🚀", "rocket launch space fast"],
  ["🛳️", "ship cruise boat travel"],
  ["⛵", "sailboat sailing boat"],
  ["🗺️", "map travel navigation"],
  ["🧳", "luggage suitcase travel trip vacation"],
  ["🏖️", "beach vacation umbrella sand"],
  ["🏕️", "camping tent outdoors"],
  ["⛰️", "mountain hiking climb"],
  ["🌋", "volcano lava"],
  ["🎁", "gift present birthday wrap"],
  ["🎂", "cake birthday celebration"],
  ["🎈", "balloon party celebration"],
  ["🎉", "party celebration confetti tada"],
  ["🎊", "confetti party celebration"],
  ["🎃", "pumpkin halloween"],
  ["🎄", "christmas tree holiday"],
  ["🎅", "santa christmas holiday"],
  ["🕎", "menorah hanukkah"],
  ["🎆", "fireworks celebration new year"],
  ["💐", "bouquet flowers gift"],
  ["🌹", "rose flower love"],
  ["🌷", "tulip flower spring"],
  ["🌻", "sunflower flower"],
  ["🌸", "cherry blossom flower spring"],
  ["🌱", "seedling plant grow garden"],
  ["🌿", "herb plant leaf"],
  ["🍀", "clover luck lucky four leaf"],
  ["🌳", "tree nature"],
  ["🌵", "cactus desert plant"],
  ["🍁", "maple leaf fall autumn"],
  ["🍂", "fallen leaves fall autumn"],
  ["☀️", "sun sunny weather"],
  ["🌤️", "sun cloud weather"],
  ["☁️", "cloud weather"],
  ["🌧️", "rain weather"],
  ["⛈️", "storm thunder lightning weather"],
  ["❄️", "snowflake snow winter cold"],
  ["⛄", "snowman winter snow"],
  ["🌈", "rainbow pride colorful"],
  ["🌊", "wave ocean water sea"],
  ["🌙", "moon night crescent"],
  ["🌎", "earth world globe planet"],
  ["💰", "money bag cash savings finance"],
  ["💵", "dollar money cash bill"],
  ["💳", "credit card payment"],
  ["🪙", "coin money"],
  ["📈", "chart up stocks growth increase"],
  ["📉", "chart down stocks decrease"],
  ["📊", "bar chart stats data"],
  ["🧾", "receipt bill taxes"],
  ["⚖️", "scale balance legal justice law"],
  ["💼", "briefcase work business job"],
  ["🩺", "stethoscope doctor medical health checkup"],
  ["💊", "pill medicine medication drug"],
  ["💉", "syringe shot vaccine injection"],
  ["🦷", "tooth dentist dental"],
  ["👓", "glasses vision eye"],
  ["🧠", "brain mind mental think"],
  ["❤️", "heart love red"],
  ["🧡", "heart orange"],
  ["💛", "heart yellow"],
  ["💚", "heart green"],
  ["💙", "heart blue"],
  ["💜", "heart purple"],
  ["🖤", "heart black"],
  ["🤍", "heart white"],
  ["💖", "heart sparkle love"],
  ["💔", "broken heart sad"],
  ["😀", "smile happy face grin"],
  ["😂", "laugh joy funny tears"],
  ["🥹", "tears grateful touched"],
  ["😊", "smile happy blush"],
  ["😎", "cool sunglasses"],
  ["🤔", "think thinking hmm"],
  ["😴", "sleep tired zzz nap"],
  ["😅", "sweat smile nervous"],
  ["🥳", "party celebrate birthday hat"],
  ["😤", "determined frustrated"],
  ["😭", "cry sad sobbing tears"],
  ["😱", "scream shocked fear"],
  ["🤯", "mind blown explode"],
  ["🤒", "sick fever ill thermometer"],
  ["🤢", "sick nausea gross"],
  ["🥶", "cold freezing"],
  ["🥵", "hot heat sweating"],
  ["🤗", "hug welcome"],
  ["🙏", "pray thanks please hands"],
  ["👍", "thumbs up good yes approve"],
  ["👎", "thumbs down bad no"],
  ["👏", "clap applause"],
  ["🤝", "handshake deal agreement"],
  ["👋", "wave hello goodbye hi"],
  ["✌️", "peace victory"],
  ["🤞", "fingers crossed luck hope"],
  ["👶", "baby infant child"],
  ["🧒", "child kid"],
  ["👨", "man person"],
  ["👩", "woman person"],
  ["🧑‍🤝‍🧑", "people friends couple together"],
  ["👪", "family parents kids"],
  ["👰", "bride wedding"],
  ["🤵", "groom wedding tuxedo"],
  ["💍", "ring engagement wedding diamond"],
  ["💒", "wedding chapel marriage"],
  ["🐶", "dog puppy pet animal"],
  ["🐱", "cat kitten pet animal"],
  ["🐭", "mouse animal"],
  ["🐹", "hamster pet animal"],
  ["🐰", "rabbit bunny animal easter"],
  ["🦊", "fox animal"],
  ["🐻", "bear animal"],
  ["🐼", "panda animal"],
  ["🐨", "koala animal"],
  ["🦁", "lion animal"],
  ["🐮", "cow animal farm"],
  ["🐷", "pig animal farm"],
  ["🐸", "frog animal"],
  ["🐵", "monkey animal"],
  ["🐔", "chicken hen animal farm"],
  ["🐦", "bird animal tweet"],
  ["🦅", "eagle bird animal"],
  ["🦆", "duck bird animal"],
  ["🦉", "owl bird night wisdom"],
  ["🐴", "horse animal riding"],
  ["🦄", "unicorn magic fantasy"],
  ["🐝", "bee honey insect"],
  ["🦋", "butterfly insect"],
  ["🐢", "turtle slow animal"],
  ["🐍", "snake animal"],
  ["🐠", "fish tropical aquarium"],
  ["🐬", "dolphin ocean animal"],
  ["🐳", "whale ocean animal"],
  ["🦈", "shark ocean animal"],
  ["🐙", "octopus ocean animal"],
  ["🦀", "crab ocean seafood"],
  ["🕷️", "spider insect web"],
  ["🍎", "apple fruit red food"],
  ["🍌", "banana fruit food"],
  ["🍇", "grapes fruit food"],
  ["🍓", "strawberry fruit food"],
  ["🍉", "watermelon fruit summer"],
  ["🍊", "orange fruit food"],
  ["🍋", "lemon fruit sour"],
  ["🍑", "peach fruit food"],
  ["🥑", "avocado food healthy"],
  ["🥦", "broccoli vegetable healthy food"],
  ["🥕", "carrot vegetable food"],
  ["🌽", "corn vegetable food"],
  ["🍞", "bread loaf bakery food"],
  ["🧀", "cheese food"],
  ["🥚", "egg food breakfast"],
  ["🥓", "bacon food breakfast"],
  ["🍔", "burger hamburger food fast"],
  ["🍟", "fries food fast"],
  ["🍕", "pizza food"],
  ["🌮", "taco food mexican"],
  ["🌯", "burrito food mexican"],
  ["🍜", "noodles ramen soup food"],
  ["🍝", "spaghetti pasta food"],
  ["🍣", "sushi food japanese"],
  ["🍦", "ice cream dessert food"],
  ["🍩", "donut dessert food"],
  ["🍪", "cookie dessert food"],
  ["🍫", "chocolate candy dessert"],
  ["🍿", "popcorn movie snack"],
  ["☕", "coffee tea drink cafe"],
  ["🍵", "tea drink green"],
  ["🥤", "soda drink cup straw"],
  ["🍺", "beer drink alcohol"],
  ["🍷", "wine drink alcohol glass"],
  ["🍸", "cocktail drink martini alcohol"],
  ["🥂", "cheers champagne toast celebrate"],
  ["🍽️", "plate dinner meal food eat restaurant"],
  ["🧹", "broom clean sweep chores"],
  ["🧺", "laundry basket chores"],
  ["🧼", "soap clean wash"],
  ["🛁", "bath bathtub clean"],
  ["🚿", "shower clean"],
  ["🧽", "sponge clean scrub"],
  ["🗑️", "trash garbage delete waste"],
  ["🔧", "wrench fix repair tool"],
  ["🔨", "hammer build repair tool"],
  ["🪛", "screwdriver fix tool"],
  ["⚙️", "gear settings machine"],
  ["🪚", "saw wood tool carpentry"],
  ["🪜", "ladder climb tool"],
  ["🔩", "bolt nut hardware"],
  ["🧰", "toolbox tools repair"],
  ["🔌", "plug electric power"],
  ["💡", "light bulb idea"],
  ["🔦", "flashlight torch light"],
  ["🕯️", "candle light"],
  ["🛒", "shopping cart groceries buy"],
  ["🛍️", "shopping bags buy retail"],
  ["👕", "shirt clothes clothing"],
  ["👗", "dress clothes clothing"],
  ["👖", "jeans pants clothes"],
  ["🧥", "coat jacket clothes"],
  ["👟", "sneaker shoe running"],
  ["👠", "heel shoe fashion"],
  ["🧢", "cap hat"],
  ["🎩", "top hat fancy"],
  ["👑", "crown king queen royal"],
  ["💄", "lipstick makeup beauty"],
  ["💅", "nails manicure beauty"],
  ["💇", "haircut salon hair"],
  ["🎵", "music note song"],
  ["🎶", "music notes song"],
  ["🎸", "guitar music instrument"],
  ["🎹", "piano music keyboard instrument"],
  ["🥁", "drums music instrument"],
  ["🎤", "microphone sing karaoke"],
  ["🎧", "headphones music listen"],
  ["🎬", "movie film clapper cinema"],
  ["🎥", "camera movie film video"],
  ["📷", "camera photo picture"],
  ["📺", "tv television show watch"],
  ["🎮", "game controller video gaming"],
  ["🕹️", "joystick game arcade"],
  ["🎲", "dice game board random"],
  ["♟️", "chess pawn game strategy"],
  ["🧩", "puzzle piece jigsaw"],
  ["🃏", "cards joker game"],
  ["🎨", "art palette paint creative"],
  ["🖌️", "paintbrush art paint"],
  ["🖍️", "crayon draw color"],
  ["🧵", "thread sewing craft"],
  ["🧶", "yarn knitting craft"],
  ["🏆", "trophy win award champion"],
  ["🥇", "gold medal first winner"],
  ["🥈", "silver medal second"],
  ["🥉", "bronze medal third"],
  ["🎖️", "medal military award"],
  ["🎓", "graduation cap school degree diploma"],
  ["🔑", "key lock unlock"],
  ["🔒", "lock secure private"],
  ["🔓", "unlock open"],
  ["🛡️", "shield protect security"],
  ["⚔️", "swords battle fight"],
  ["🏹", "bow arrow archery"],
  ["🧭", "compass navigation direction"],
  ["⌚", "watch time wrist"],
  ["⏱️", "stopwatch timer time"],
  ["🔔", "bell notification alert reminder"],
  ["🔕", "bell mute silence"],
  ["📢", "megaphone announce loud"],
  ["💬", "speech bubble chat message talk"],
  ["💭", "thought bubble think"],
  ["🗨️", "speech chat message"],
  ["❓", "question mark help"],
  ["❗", "exclamation important alert"],
  ["⚠️", "warning caution alert"],
  ["🚫", "no forbidden stop prohibited"],
  ["♻️", "recycle green environment"],
  ["🔄", "refresh repeat cycle sync"],
  ["➕", "plus add new"],
  ["➖", "minus subtract remove"],
  ["💯", "hundred perfect score"],
  ["🔟", "ten number"],
  ["🅰️", "letter a"],
  ["🅱️", "letter b"],
  ["🆗", "ok okay"],
  ["🆕", "new"],
  ["🆙", "up level"],
  // ---- Smileys & emotion ----
  ["😃", "smile happy big grin"],
  ["😄", "smile happy laugh eyes"],
  ["😁", "grin beaming teeth"],
  ["😆", "laugh squint haha"],
  ["🤣", "rofl rolling laughing floor"],
  ["🙂", "slight smile ok"],
  ["🙃", "upside down silly sarcastic"],
  ["😉", "wink flirt"],
  ["😇", "innocent halo angel"],
  ["🥰", "love hearts adore smiling"],
  ["😍", "heart eyes love crush"],
  ["🤩", "star struck excited wow"],
  ["😘", "kiss blow love"],
  ["😗", "kiss"],
  ["😋", "yum tasty delicious tongue"],
  ["😛", "tongue out playful"],
  ["😜", "wink tongue crazy silly"],
  ["🤪", "zany crazy wild goofy"],
  ["🤑", "money face rich dollar"],
  ["🤭", "giggle hand over mouth oops"],
  ["🤫", "shush quiet secret"],
  ["😐", "neutral meh blank"],
  ["😑", "expressionless blank annoyed"],
  ["😶", "no mouth speechless silence"],
  ["😏", "smirk sly"],
  ["😒", "unamused annoyed meh"],
  ["🙄", "eye roll whatever annoyed"],
  ["😬", "grimace awkward cringe teeth"],
  ["🤥", "lying liar pinocchio nose"],
  ["😌", "relieved calm peaceful content"],
  ["😔", "pensive sad thoughtful"],
  ["😪", "sleepy tired tear"],
  ["🤤", "drooling hungry want"],
  ["😷", "mask sick doctor covid"],
  ["🤕", "hurt injured bandage head"],
  ["🤧", "sneeze sick tissue cold"],
  ["🥴", "woozy dizzy drunk tipsy"],
  ["😵", "dizzy knocked out crossed eyes"],
  ["🤠", "cowboy hat yeehaw western"],
  ["🥸", "disguise glasses mustache incognito"],
  ["🤓", "nerd geek glasses smart"],
  ["🧐", "monocle inspect curious fancy"],
  ["😕", "confused unsure"],
  ["😟", "worried concerned"],
  ["🙁", "frown sad slightly"],
  ["😮", "open mouth wow surprised"],
  ["😯", "hushed surprised"],
  ["😲", "astonished shocked gasp"],
  ["🥺", "pleading puppy eyes beg cute"],
  ["😢", "cry sad tear"],
  ["😥", "sad relieved disappointed sweat"],
  ["😰", "anxious sweat nervous cold"],
  ["😨", "fearful scared afraid"],
  ["😳", "flushed embarrassed blush shocked"],
  ["😖", "confounded frustrated scrunched"],
  ["😣", "persevere struggling effort"],
  ["😞", "disappointed sad let down"],
  ["😓", "downcast sweat tired hard"],
  ["😩", "weary tired exhausted ugh"],
  ["😫", "tired exhausted fed up"],
  ["🥱", "yawn tired bored sleepy"],
  ["😡", "angry rage mad red"],
  ["😠", "angry mad annoyed"],
  ["🤬", "cursing swearing angry symbols"],
  ["😈", "devil smiling purple mischief"],
  ["👿", "devil angry imp"],
  ["💀", "skull dead death"],
  ["☠️", "skull crossbones danger poison death"],
  ["💩", "poop poo funny"],
  ["🤡", "clown circus creepy"],
  ["👹", "ogre monster japanese"],
  ["👻", "ghost halloween boo spooky"],
  ["👽", "alien ufo space extraterrestrial"],
  ["🤖", "robot bot ai machine"],
  ["😺", "cat smile happy"],
  ["😸", "cat grin happy"],
  ["😹", "cat laugh joy tears"],
  ["😻", "cat heart eyes love"],
  ["😿", "cat cry sad tear"],
  ["🙈", "monkey see no evil hide eyes"],
  ["🙉", "monkey hear no evil ears"],
  ["🙊", "monkey speak no evil mouth quiet"],
  ["💋", "kiss lips lipstick mark"],
  ["💌", "love letter heart mail"],
  ["💘", "heart arrow cupid love"],
  ["💝", "heart ribbon gift love"],
  ["💗", "heart growing love pink"],
  ["💓", "heart beating love pulse"],
  ["💞", "hearts revolving love"],
  ["💕", "hearts two love pink"],
  ["💟", "heart decoration love"],
  ["❣️", "heart exclamation love"],
  ["💤", "zzz sleep snore nap"],
  ["💢", "anger symbol mad comic"],
  ["💥", "boom explosion collision bang"],
  ["💫", "dizzy stars swirl"],
  ["💦", "sweat droplets water splash"],
  ["💨", "dash wind fast smoke zoom"],
  ["🕳️", "hole black void"],
  ["🗯️", "speech bubble angry shout"],
  // ---- Gestures & body ----
  ["🤌", "pinched fingers italian chef kiss"],
  ["🤏", "pinch small tiny little bit"],
  ["🤟", "love you sign rock hand"],
  ["🤘", "rock on horns metal"],
  ["🤙", "call me shaka hang loose"],
  ["👈", "point left finger"],
  ["👉", "point right finger"],
  ["👆", "point up finger"],
  ["👇", "point down finger"],
  ["☝️", "point up one first"],
  ["✋", "hand stop high five raised"],
  ["🤚", "hand raised back"],
  ["🖐️", "hand fingers spread five"],
  ["🖖", "vulcan spock star trek"],
  ["👌", "ok okay perfect fingers"],
  ["✊", "fist power solidarity bump"],
  ["👊", "fist bump punch"],
  ["🤛", "fist left bump"],
  ["🤜", "fist right bump"],
  ["🤲", "palms up together prayer offer"],
  ["👐", "open hands hug"],
  ["🙌", "raised hands celebration praise hooray"],
  ["✍️", "writing hand sign"],
  ["🦵", "leg kick"],
  ["🦶", "foot kick step"],
  ["👂", "ear listen hear"],
  ["👃", "nose smell"],
  ["👀", "eyes look watch see"],
  ["👁️", "eye look single"],
  ["👅", "tongue taste lick"],
  ["👄", "mouth lips"],
  ["🦾", "mechanical arm prosthetic robot"],
  ["🧑", "person adult"],
  ["👴", "old man grandpa elderly"],
  ["👵", "old woman grandma elderly"],
  ["👦", "boy kid child"],
  ["👧", "girl kid child"],
  ["🧔", "beard person man"],
  ["👱", "blond person"],
  ["🧓", "older person elderly"],
  ["👮", "police officer cop"],
  ["👷", "construction worker builder hard hat"],
  ["💂", "guard british royal"],
  ["🕵️", "detective spy investigate sleuth"],
  ["🧑‍⚕️", "doctor nurse health medical worker"],
  ["🧑‍🌾", "farmer gardener agriculture"],
  ["🧑‍🍳", "chef cook kitchen"],
  ["🧑‍🎓", "student graduate school"],
  ["🧑‍🎤", "singer rockstar musician performer"],
  ["🧑‍🏫", "teacher professor school"],
  ["🧑‍🏭", "factory worker welder"],
  ["🧑‍💻", "programmer developer coder technologist"],
  ["🧑‍💼", "office worker business professional"],
  ["🧑‍🔧", "mechanic plumber repair"],
  ["🧑‍🔬", "scientist lab researcher"],
  ["🧑‍🎨", "artist painter creative"],
  ["🧑‍🚒", "firefighter fire"],
  ["🧑‍✈️", "pilot aviation plane"],
  ["🧑‍🚀", "astronaut space nasa"],
  ["🧑‍⚖️", "judge court law justice"],
  ["🦸", "superhero hero cape"],
  ["🦹", "villain supervillain"],
  ["🧙", "wizard mage magic gandalf"],
  ["🧚", "fairy pixie wings"],
  ["🧛", "vampire dracula halloween"],
  ["🧜", "mermaid merman ocean"],
  ["🧟", "zombie undead halloween"],
  ["💆", "massage spa relax head"],
  ["💃", "dancer dancing woman salsa"],
  ["🕺", "dancer dancing man disco"],
  ["🚶", "walking person walk stroll"],
  ["🧎", "kneeling person knee"],
  ["🏇", "horse racing jockey"],
  ["⛷️", "skier ski snow"],
  ["🏂", "snowboarder snowboard snow"],
  ["🏌️", "golfer golf swing"],
  ["🏄", "surfer surfing wave"],
  ["🚣", "rowing boat row"],
  ["🧗", "climbing climber rock"],
  ["🤸", "cartwheel gymnastics flip"],
  ["🤼", "wrestling wrestlers fight"],
  ["🤽", "water polo swim"],
  ["🤾", "handball sport"],
  ["🤹", "juggling juggler circus"],
  ["🛀", "bath bathtub relax soak"],
  ["🛌", "bed sleeping person sleep"],
  // ---- Animals & nature extras ----
  ["🐺", "wolf animal howl"],
  ["🐗", "boar pig wild"],
  ["🐛", "bug caterpillar insect"],
  ["🐜", "ant insect"],
  ["🪲", "beetle insect bug"],
  ["🐞", "ladybug insect luck"],
  ["🦗", "cricket insect"],
  ["🦂", "scorpion sting"],
  ["🦟", "mosquito bug bite"],
  ["🐌", "snail slow"],
  ["🐚", "shell beach seashell"],
  ["🦑", "squid ocean"],
  ["🦞", "lobster seafood"],
  ["🦐", "shrimp seafood prawn"],
  ["🐡", "blowfish puffer fish"],
  ["🐟", "fish animal"],
  ["🦭", "seal animal ocean"],
  ["🐊", "crocodile alligator"],
  ["🦎", "lizard gecko reptile"],
  ["🦖", "trex dinosaur"],
  ["🦕", "dinosaur sauropod longneck"],
  ["🐋", "whale big ocean"],
  ["🦧", "orangutan ape"],
  ["🦍", "gorilla ape"],
  ["🐘", "elephant animal"],
  ["🦛", "hippo hippopotamus"],
  ["🦏", "rhino rhinoceros"],
  ["🐪", "camel desert"],
  ["🦒", "giraffe animal tall"],
  ["🦘", "kangaroo australia"],
  ["🐃", "buffalo water animal"],
  ["🐂", "ox bull animal"],
  ["🐄", "cow dairy farm"],
  ["🐎", "horse gallop fast"],
  ["🐖", "pig farm animal"],
  ["🐏", "ram sheep animal"],
  ["🐑", "sheep ewe wool"],
  ["🦙", "llama alpaca"],
  ["🐐", "goat animal"],
  ["🦌", "deer animal antlers"],
  ["🐕", "dog pet animal"],
  ["🐩", "poodle dog fancy"],
  ["🦮", "guide dog service"],
  ["🐈", "cat pet animal"],
  ["🐓", "rooster chicken farm"],
  ["🦃", "turkey thanksgiving bird"],
  ["🦚", "peacock bird feathers"],
  ["🦜", "parrot bird tropical"],
  ["🦢", "swan bird elegant"],
  ["🦩", "flamingo pink bird"],
  ["🕊️", "dove peace bird"],
  ["🐇", "rabbit bunny fast"],
  ["🦝", "raccoon trash panda"],
  ["🦨", "skunk smell"],
  ["🦡", "badger animal"],
  ["🦫", "beaver dam animal"],
  ["🦦", "otter animal cute"],
  ["🦥", "sloth slow lazy"],
  ["🐁", "mouse animal small"],
  ["🐀", "rat animal"],
  ["🦔", "hedgehog animal spiky"],
  ["🐾", "paw prints animal tracks pet"],
  ["🐉", "dragon fantasy"],
  ["🌲", "evergreen tree pine forest"],
  ["🌴", "palm tree tropical beach"],
  ["🌾", "wheat grain rice harvest"],
  ["🌺", "hibiscus flower tropical"],
  ["🌼", "daisy blossom flower"],
  ["🪴", "potted plant houseplant"],
  ["🍄", "mushroom fungus toadstool"],
  ["🌰", "chestnut nut"],
  ["🪵", "wood log lumber"],
  ["🌍", "earth europe africa globe"],
  ["🌏", "earth asia australia globe"],
  ["🪐", "saturn planet rings space"],
  ["🌑", "new moon dark"],
  ["🌕", "full moon bright"],
  ["🌗", "half moon quarter"],
  ["☄️", "comet meteor space"],
  ["🌠", "shooting star wish night"],
  ["⚡", "lightning bolt electric zap power"],
  ["🌪️", "tornado storm twister"],
  ["🌫️", "fog mist weather"],
  ["🌬️", "wind blow face weather"],
  ["🌡️", "thermometer temperature hot fever"],
  ["☂️", "umbrella rain"],
  ["💧", "droplet water drop"],
  // ---- Food & drink extras ----
  ["🍍", "pineapple fruit tropical"],
  ["🥭", "mango fruit tropical"],
  ["🍒", "cherries fruit red"],
  ["🍈", "melon fruit"],
  ["🍐", "pear fruit"],
  ["🥝", "kiwi fruit green"],
  ["🍅", "tomato vegetable fruit"],
  ["🥥", "coconut tropical"],
  ["🍆", "eggplant aubergine vegetable"],
  ["🥔", "potato vegetable"],
  ["🧄", "garlic cooking"],
  ["🧅", "onion cooking"],
  ["🌶️", "hot pepper spicy chili"],
  ["🥒", "cucumber pickle vegetable"],
  ["🥬", "lettuce leafy greens kale"],
  ["🥜", "peanuts nuts"],
  ["🥐", "croissant pastry french breakfast"],
  ["🥖", "baguette bread french"],
  ["🥨", "pretzel snack"],
  ["🥯", "bagel breakfast"],
  ["🥞", "pancakes breakfast syrup"],
  ["🧇", "waffle breakfast"],
  ["🍗", "chicken leg poultry drumstick"],
  ["🍖", "meat bone ribs"],
  ["🥩", "steak meat beef"],
  ["🌭", "hot dog food"],
  ["🥪", "sandwich lunch food"],
  ["🥙", "pita wrap stuffed flatbread"],
  ["🧆", "falafel food"],
  ["🥘", "paella pan food shallow"],
  ["🍲", "stew pot food soup"],
  ["🥗", "salad green healthy bowl"],
  ["🍱", "bento box japanese lunch"],
  ["🍘", "rice cracker japanese"],
  ["🍙", "onigiri rice ball japanese"],
  ["🍚", "rice bowl cooked"],
  ["🍛", "curry rice food"],
  ["🍤", "fried shrimp tempura"],
  ["🍥", "fish cake narutomaki"],
  ["🥮", "moon cake festival"],
  ["🍡", "dango dumpling skewer sweet"],
  ["🥟", "dumpling potsticker gyoza"],
  ["🥠", "fortune cookie chinese"],
  ["🍨", "ice cream sundae dessert"],
  ["🍧", "shaved ice dessert"],
  ["🍰", "cake slice shortcake dessert"],
  ["🧁", "cupcake dessert sweet"],
  ["🥧", "pie dessert"],
  ["🍬", "candy sweet"],
  ["🍭", "lollipop candy sweet"],
  ["🍮", "custard flan pudding dessert"],
  ["🍯", "honey pot sweet"],
  ["🍼", "baby bottle milk"],
  ["🥛", "milk glass drink"],
  ["🫖", "teapot tea brew"],
  ["🍶", "sake japanese drink"],
  ["🍾", "champagne bottle pop celebrate"],
  ["🥃", "whiskey tumbler drink scotch"],
  ["🧃", "juice box drink"],
  ["🧋", "boba bubble tea drink"],
  ["🥢", "chopsticks eat"],
  ["🥄", "spoon eat"],
  ["🔪", "knife cut kitchen"],
  // ---- Travel & places extras ----
  ["🏔️", "snow mountain peak"],
  ["🏜️", "desert sand dry"],
  ["🏝️", "desert island tropical beach"],
  ["🏟️", "stadium arena sports"],
  ["🏗️", "construction crane building"],
  ["🏘️", "houses neighborhood"],
  ["🏚️", "derelict house abandoned"],
  ["🏭", "factory industry"],
  ["🏨", "hotel lodging"],
  ["🏪", "convenience store shop"],
  ["🏬", "department store mall"],
  ["🏯", "castle japanese"],
  ["🏰", "castle european fairy tale"],
  ["🗼", "tower tokyo"],
  ["🗽", "statue liberty new york"],
  ["🕌", "mosque islam"],
  ["🕍", "synagogue jewish"],
  ["🛕", "hindu temple"],
  ["⛩️", "shinto shrine torii japan"],
  ["♨️", "hot springs onsen spa"],
  ["🎠", "carousel horse fair"],
  ["🎡", "ferris wheel fair amusement"],
  ["🎢", "roller coaster amusement park"],
  ["💈", "barber pole haircut"],
  ["🎪", "circus tent big top"],
  ["🚃", "railway car train"],
  ["🚄", "bullet train fast shinkansen"],
  ["🚈", "light rail metro"],
  ["🚇", "metro subway underground"],
  ["🚎", "trolleybus transit"],
  ["🚐", "minibus van"],
  ["🚑", "ambulance emergency medical"],
  ["🚒", "fire engine truck emergency"],
  ["🚓", "police car cop"],
  ["🛻", "pickup truck"],
  ["🚚", "delivery truck shipping"],
  ["🚜", "tractor farm"],
  ["🏎️", "race car f1 fast"],
  ["🏍️", "motorcycle bike fast"],
  ["🛵", "scooter vespa moped"],
  ["🦽", "wheelchair manual"],
  ["🛺", "auto rickshaw tuk tuk"],
  ["🚲", "bicycle bike cycle"],
  ["🛴", "kick scooter"],
  ["🚏", "bus stop"],
  ["⛽", "fuel gas pump station"],
  ["🚨", "police light siren emergency alert"],
  ["🚥", "traffic light horizontal"],
  ["🚦", "traffic light vertical stoplight"],
  ["🛑", "stop sign halt"],
  ["🚧", "construction barrier roadwork"],
  ["⚓", "anchor ship sea"],
  ["🛶", "canoe kayak paddle"],
  ["🚤", "speedboat boat fast"],
  ["🛥️", "motor boat yacht"],
  ["🚢", "ship cruise big"],
  ["🛩️", "small plane aircraft"],
  ["🛫", "plane takeoff departure"],
  ["🛬", "plane landing arrival"],
  ["🪂", "parachute skydive"],
  ["💺", "seat airplane chair"],
  ["🚁", "helicopter chopper"],
  ["🚠", "cable car gondola mountain"],
  ["🛰️", "satellite space orbit"],
  ["🛸", "ufo flying saucer alien"],
  ["🌃", "night city stars skyline"],
  ["🌆", "cityscape dusk sunset buildings"],
  ["🌇", "sunset city"],
  ["🌉", "bridge night golden gate"],
  ["🗻", "mount fuji mountain japan"],
  ["⛺", "tent camping"],
  ["🌅", "sunrise ocean morning"],
  ["🎑", "moon viewing festival grass"],
  ["🏞️", "national park nature river"],
  // ---- Objects extras ----
  ["📀", "dvd disc"],
  ["💿", "cd disc"],
  ["💾", "floppy disk save"],
  ["📼", "vhs videotape cassette"],
  ["📻", "radio music broadcast"],
  ["🎙️", "studio microphone podcast recording"],
  ["🎚️", "level slider audio"],
  ["🎛️", "control knobs mixer audio"],
  ["⏲️", "timer clock kitchen"],
  ["🕰️", "mantel clock antique time"],
  ["⌛", "hourglass done time sand"],
  ["📡", "satellite dish antenna signal"],
  ["🔋", "battery power charge"],
  ["🪫", "low battery dying power"],
  ["🖨️", "printer print"],
  ["🖲️", "trackball computer"],
  ["🗜️", "clamp compress vise"],
  ["📸", "camera flash photo selfie"],
  ["🔍", "magnifying glass search left zoom"],
  ["🔎", "magnifying glass search right zoom"],
  ["🪞", "mirror reflection"],
  ["🪟", "window glass"],
  ["🛋️", "couch sofa lamp living room"],
  ["🪑", "chair seat"],
  ["🚪", "door entrance exit"],
  ["🛏️", "bed sleep bedroom"],
  ["🧸", "teddy bear toy plush"],
  ["🪆", "nesting dolls matryoshka russian"],
  ["🖼️", "framed picture painting art"],
  ["🪅", "pinata party mexican"],
  ["🎀", "ribbon bow pink gift"],
  ["🪄", "magic wand wizard spell"],
  ["🎏", "carp streamer flags japanese"],
  ["🎎", "japanese dolls festival"],
  ["🏮", "red paper lantern japanese"],
  ["🎐", "wind chime bell japanese"],
  ["🧧", "red envelope lucky money chinese"],
  ["📯", "postal horn"],
  ["📪", "mailbox closed mail"],
  ["📫", "mailbox mail flag up"],
  ["📬", "mailbox open mail"],
  ["🗳️", "ballot box vote election"],
  ["🖋️", "fountain pen fancy write"],
  ["📄", "page document paper file"],
  ["📃", "page curl document"],
  ["📑", "bookmark tabs document"],
  ["📜", "scroll paper ancient document"],
  ["📇", "card index rolodex contacts"],
  ["🗂️", "card index dividers files organize"],
  ["📂", "folder open files"],
  ["📁", "folder files"],
  ["🗞️", "newspaper rolled news"],
  ["📰", "newspaper news"],
  ["📕", "book red closed"],
  ["📗", "book green"],
  ["📘", "book blue"],
  ["📙", "book orange"],
  ["📔", "notebook decorative cover"],
  ["📒", "ledger notebook yellow"],
  ["📏", "ruler straight measure"],
  ["📐", "triangle ruler measure"],
  ["✂️", "scissors cut"],
  ["📎", "paperclip attach"],
  ["🖇️", "paperclips linked attach"],
  ["📋", "clipboard list tasks"],
  ["🗒️", "spiral notepad notes"],
  ["📆", "tear off calendar date"],
  ["🔗", "link chain url connect"],
  ["⛓️", "chains linked metal"],
  ["🧲", "magnet attract"],
  ["🪝", "hook catch"],
  ["🧪", "test tube science experiment lab"],
  ["🧫", "petri dish science lab culture"],
  ["🧬", "dna genetics biology helix"],
  ["🔬", "microscope science lab"],
  ["🔭", "telescope astronomy stars"],
  ["🩹", "bandage bandaid heal"],
  ["🩼", "crutch injury walking aid"],
  ["🩻", "xray bones radiology"],
  ["🚽", "toilet bathroom"],
  ["🪠", "plunger toilet unclog"],
  ["🪣", "bucket pail"],
  ["🪥", "toothbrush dental teeth"],
  ["🪒", "razor shave"],
  ["🧴", "lotion bottle shampoo soap"],
  ["🛎️", "bellhop bell hotel service"],
  ["🧷", "safety pin"],
  ["🧿", "nazar amulet evil eye bead"],
  ["📿", "prayer beads rosary"],
  ["💎", "gem diamond jewel precious"],
  ["🫙", "jar container empty"],
  ["🧊", "ice cube cold frozen"],
  ["⚱️", "urn funeral"],
  ["🪦", "headstone grave rip tombstone"],
  ["🗿", "moai statue easter island stone"],
  // ---- Symbols & misc ----
  ["🛜", "wifi wireless internet signal"],
  ["🔅", "dim brightness low"],
  ["🔆", "bright brightness high"],
  ["📶", "signal bars cell reception"],
  ["📳", "vibration mode phone"],
  ["♾️", "infinity forever endless"],
  ["✖️", "multiply x cross"],
  ["➗", "divide division"],
  ["🟰", "equals math"],
  ["💱", "currency exchange money"],
  ["™️", "trademark tm"],
  ["©️", "copyright"],
  ["🔞", "eighteen adults only nsfw"],
  ["📵", "no phones forbidden"],
  ["🚭", "no smoking forbidden"],
  ["❌", "cross x no wrong"],
  ["⭕", "circle o correct hollow red"],
  ["🛐", "worship religion place"],
  ["☮️", "peace sign symbol"],
  ["☯️", "yin yang balance tao"],
  ["✝️", "cross christian latin"],
  ["☪️", "star crescent islam"],
  ["🕉️", "om hindu symbol"],
  ["✡️", "star david jewish"],
  ["♈", "aries zodiac ram"],
  ["♉", "taurus zodiac bull"],
  ["♊", "gemini zodiac twins"],
  ["♋", "cancer zodiac crab"],
  ["♌", "leo zodiac lion"],
  ["♍", "virgo zodiac"],
  ["♎", "libra zodiac scales"],
  ["♏", "scorpio zodiac scorpion"],
  ["♐", "sagittarius zodiac archer"],
  ["♑", "capricorn zodiac goat"],
  ["♒", "aquarius zodiac water"],
  ["♓", "pisces zodiac fish"],
  ["🔀", "shuffle random crossed arrows"],
  ["🔁", "repeat loop arrows"],
  ["🔂", "repeat one loop single"],
  ["▶️", "play start button"],
  ["⏯️", "play pause button toggle"],
  ["⏸️", "pause button break"],
  ["⏹️", "stop button square"],
  ["⏺️", "record button circle"],
  ["⏭️", "next track skip"],
  ["⏮️", "previous track back"],
  ["⏩", "fast forward speed"],
  ["⏪", "rewind back"],
  ["🔼", "up triangle button"],
  ["🔽", "down triangle button"],
  ["🆓", "free"],
  ["🆒", "cool"],
  ["🈴", "japanese passing grade"],
  ["🚾", "wc water closet restroom"],
  ["🅿️", "parking p"],
  ["🚻", "restroom bathroom toilets"],
  ["♿", "wheelchair accessible disability"],
  ["🚼", "baby symbol nursery"],
  ["🛗", "elevator lift"],
  ["🔠", "capital letters abc uppercase"],
  ["🔤", "letters alphabet abc"],
  ["🔣", "symbols input"],
  ["🎦", "cinema movie film"],
  ["🀄", "mahjong red dragon tile"],
  ["🎴", "flower playing cards hanafuda"],
  ["🕐", "one oclock clock"],
  ["🕒", "three oclock clock"],
  ["🕕", "six oclock clock"],
  ["🕘", "nine oclock clock"],
  ["🕛", "twelve oclock clock noon midnight"],
  ["🟥", "red square block"],
  ["🟧", "orange square block"],
  ["🟨", "yellow square block"],
  ["🟩", "green square block"],
  ["🟦", "blue square block"],
  ["🟪", "purple square block"],
  ["⬛", "black square block"],
  ["⬜", "white square block"],
  ["🔴", "red circle dot"],
  ["🟠", "orange circle dot"],
  ["🟡", "yellow circle dot"],
  ["🟢", "green circle dot"],
  ["🔵", "blue circle dot"],
  ["🟣", "purple circle dot"],
  ["⚫", "black circle dot"],
  ["⚪", "white circle dot"],
  ["🔶", "orange diamond large"],
  ["🔷", "blue diamond large"],
  ["🔺", "red triangle up"],
  ["🔻", "red triangle down"],
  ["🏁", "checkered flag race finish"],
  ["🚩", "red flag warning marker"],
  ["🏳️", "white flag surrender"],
  ["🏴", "black flag"],
  ["🏳️‍🌈", "rainbow flag pride lgbt"],
  ["🏴‍☠️", "pirate flag jolly roger skull"],
];
