// Searchable emoji library: [emoji, "space-separated keywords"]
// Star is first so it's the default/top pick.
export const EMOJI_DATA = [
  ["⭐", "star favorite"],
  ["🌟", "star glowing sparkle"],
  ["✨", "sparkles magic clean"],
  ["✅", "check done complete yes"],
  ["🔥", "fire hot streak urgent"],
  ["🎯", "target goal bullseye dart"],
  ["📌", "pin location important"],
  ["📍", "pin map location"],
  ["📅", "calendar date schedule"],
  ["🗓️", "calendar date schedule"],
  ["⏰", "alarm clock time"],
  ["⏳", "hourglass time waiting"],
  ["💪", "muscle strong gym workout fitness"],
  ["🏃", "run running exercise jog"],
  ["🚴", "bike cycling bicycle exercise"],
  ["🏋️", "weights lifting gym workout"],
  ["🧘", "yoga meditate zen calm"],
  ["🏊", "swim swimming pool"],
  ["⚽", "soccer football sports ball"],
  ["🏀", "basketball sports ball"],
  ["🏈", "football sports ball"],
  ["⚾", "baseball sports ball"],
  ["🎾", "tennis sports ball"],
  ["🏐", "volleyball sports ball"],
  ["🥊", "boxing gloves fight"],
  ["⛳", "golf flag sports"],
  ["🎿", "ski skiing snow winter"],
  ["🛹", "skateboard skate"],
  ["📚", "books reading study school"],
  ["📖", "book reading open"],
  ["📓", "notebook journal notes"],
  ["✏️", "pencil write edit"],
  ["🖊️", "pen write"],
  ["📝", "memo note writing list"],
  ["💻", "laptop computer work code"],
  ["🖥️", "desktop computer monitor"],
  ["⌨️", "keyboard typing"],
  ["🖱️", "mouse computer"],
  ["📱", "phone mobile smartphone"],
  ["☎️", "telephone phone call"],
  ["📞", "phone call receiver"],
  ["📧", "email mail message"],
  ["✉️", "envelope mail letter"],
  ["📦", "package box shipping delivery"],
  ["🏠", "house home"],
  ["🏡", "house home garden"],
  ["🏢", "office building work"],
  ["🏥", "hospital medical health"],
  ["🏦", "bank money finance"],
  ["🏫", "school education"],
  ["⛪", "church religion"],
  ["🏛️", "government museum classical"],
  ["🚗", "car auto vehicle drive"],
  ["🚙", "suv car vehicle"],
  ["🚕", "taxi cab car"],
  ["🚌", "bus transit"],
  ["🚂", "train locomotive"],
  ["✈️", "airplane flight travel trip"],
  ["🚀", "rocket launch space fast"],
  ["🛳️", "ship cruise boat travel"],
  ["⛵", "sailboat sailing boat"],
  ["🗺️", "map travel navigation"],
  ["🧳", "luggage suitcase travel trip vacation"],
  ["🏖️", "beach vacation umbrella sand"],
  ["🏕️", "camping tent outdoors"],
  ["⛰️", "mountain hiking climb"],
  ["🌋", "volcano lava"],
  ["🎁", "gift present birthday wrap"],
  ["🎂", "cake birthday celebration"],
  ["🎈", "balloon party celebration"],
  ["🎉", "party celebration confetti tada"],
  ["🎊", "confetti party celebration"],
  ["🎃", "pumpkin halloween"],
  ["🎄", "christmas tree holiday"],
  ["🎅", "santa christmas holiday"],
  ["🕎", "menorah hanukkah"],
  ["🎆", "fireworks celebration new year"],
  ["💐", "bouquet flowers gift"],
  ["🌹", "rose flower love"],
  ["🌷", "tulip flower spring"],
  ["🌻", "sunflower flower"],
  ["🌸", "cherry blossom flower spring"],
  ["🌱", "seedling plant grow garden"],
  ["🌿", "herb plant leaf"],
  ["🍀", "clover luck lucky four leaf"],
  ["🌳", "tree nature"],
  ["🌵", "cactus desert plant"],
  ["🍁", "maple leaf fall autumn"],
  ["🍂", "fallen leaves fall autumn"],
  ["☀️", "sun sunny weather"],
  ["🌤️", "sun cloud weather"],
  ["☁️", "cloud weather"],
  ["🌧️", "rain weather"],
  ["⛈️", "storm thunder lightning weather"],
  ["❄️", "snowflake snow winter cold"],
  ["⛄", "snowman winter snow"],
  ["🌈", "rainbow pride colorful"],
  ["🌊", "wave ocean water sea"],
  ["🌙", "moon night crescent"],
  ["🌎", "earth world globe planet"],
  ["💰", "money bag cash savings finance"],
  ["💵", "dollar money cash bill"],
  ["💳", "credit card payment"],
  ["🪙", "coin money"],
  ["📈", "chart up stocks growth increase"],
  ["📉", "chart down stocks decrease"],
  ["📊", "bar chart stats data"],
  ["🧾", "receipt bill taxes"],
  ["⚖️", "scale balance legal justice law"],
  ["💼", "briefcase work business job"],
  ["🩺", "stethoscope doctor medical health checkup"],
  ["💊", "pill medicine medication drug"],
  ["💉", "syringe shot vaccine injection"],
  ["🦷", "tooth dentist dental"],
  ["👓", "glasses vision eye"],
  ["🧠", "brain mind mental think"],
  ["❤️", "heart love red"],
  ["🧡", "heart orange"],
  ["💛", "heart yellow"],
  ["💚", "heart green"],
  ["💙", "heart blue"],
  ["💜", "heart purple"],
  ["🖤", "heart black"],
  ["🤍", "heart white"],
  ["💖", "heart sparkle love"],
  ["💔", "broken heart sad"],
  ["😀", "smile happy face grin"],
  ["😂", "laugh joy funny tears"],
  ["🥹", "tears grateful touched"],
  ["😊", "smile happy blush"],
  ["😎", "cool sunglasses"],
  ["🤔", "think thinking hmm"],
  ["😴", "sleep tired zzz nap"],
  ["😅", "sweat smile nervous"],
  ["🥳", "party celebrate birthday hat"],
  ["😤", "determined frustrated"],
  ["😭", "cry sad sobbing tears"],
  ["😱", "scream shocked fear"],
  ["🤯", "mind blown explode"],
  ["🤒", "sick fever ill thermometer"],
  ["🤢", "sick nausea gross"],
  ["🥶", "cold freezing"],
  ["🥵", "hot heat sweating"],
  ["🤗", "hug welcome"],
  ["🙏", "pray thanks please hands"],
  ["👍", "thumbs up good yes approve"],
  ["👎", "thumbs down bad no"],
  ["👏", "clap applause"],
  ["🤝", "handshake deal agreement"],
  ["👋", "wave hello goodbye hi"],
  ["✌️", "peace victory"],
  ["🤞", "fingers crossed luck hope"],
  ["👶", "baby infant child"],
  ["🧒", "child kid"],
  ["👨", "man person"],
  ["👩", "woman person"],
  ["🧑‍🤝‍🧑", "people friends couple together"],
  ["👪", "family parents kids"],
  ["👰", "bride wedding"],
  ["🤵", "groom wedding tuxedo"],
  ["💍", "ring engagement wedding diamond"],
  ["💒", "wedding chapel marriage"],
  ["🐶", "dog puppy pet animal"],
  ["🐱", "cat kitten pet animal"],
  ["🐭", "mouse animal"],
  ["🐹", "hamster pet animal"],
  ["🐰", "rabbit bunny animal easter"],
  ["🦊", "fox animal"],
  ["🐻", "bear animal"],
  ["🐼", "panda animal"],
  ["🐨", "koala animal"],
  ["🦁", "lion animal"],
  ["🐮", "cow animal farm"],
  ["🐷", "pig animal farm"],
  ["🐸", "frog animal"],
  ["🐵", "monkey animal"],
  ["🐔", "chicken hen animal farm"],
  ["🐦", "bird animal tweet"],
  ["🦅", "eagle bird animal"],
  ["🦆", "duck bird animal"],
  ["🦉", "owl bird night wisdom"],
  ["🐴", "horse animal riding"],
  ["🦄", "unicorn magic fantasy"],
  ["🐝", "bee honey insect"],
  ["🦋", "butterfly insect"],
  ["🐢", "turtle slow animal"],
  ["🐍", "snake animal"],
  ["🐠", "fish tropical aquarium"],
  ["🐬", "dolphin ocean animal"],
  ["🐳", "whale ocean animal"],
  ["🦈", "shark ocean animal"],
  ["🐙", "octopus ocean animal"],
  ["🦀", "crab ocean seafood"],
  ["🕷️", "spider insect web"],
  ["🍎", "apple fruit red food"],
  ["🍌", "banana fruit food"],
  ["🍇", "grapes fruit food"],
  ["🍓", "strawberry fruit food"],
  ["🍉", "watermelon fruit summer"],
  ["🍊", "orange fruit food"],
  ["🍋", "lemon fruit sour"],
  ["🍑", "peach fruit food"],
  ["🥑", "avocado food healthy"],
  ["🥦", "broccoli vegetable healthy food"],
  ["🥕", "carrot vegetable food"],
  ["🌽", "corn vegetable food"],
  ["🍞", "bread loaf bakery food"],
  ["🧀", "cheese food"],
  ["🥚", "egg food breakfast"],
  ["🥓", "bacon food breakfast"],
  ["🍔", "burger hamburger food fast"],
  ["🍟", "fries food fast"],
  ["🍕", "pizza food"],
  ["🌮", "taco food mexican"],
  ["🌯", "burrito food mexican"],
  ["🍜", "noodles ramen soup food"],
  ["🍝", "spaghetti pasta food"],
  ["🍣", "sushi food japanese"],
  ["🍦", "ice cream dessert food"],
  ["🍩", "donut dessert food"],
  ["🍪", "cookie dessert food"],
  ["🍫", "chocolate candy dessert"],
  ["🍿", "popcorn movie snack"],
  ["☕", "coffee tea drink cafe"],
  ["🍵", "tea drink green"],
  ["🥤", "soda drink cup straw"],
  ["🍺", "beer drink alcohol"],
  ["🍷", "wine drink alcohol glass"],
  ["🍸", "cocktail drink martini alcohol"],
  ["🥂", "cheers champagne toast celebrate"],
  ["🍽️", "plate dinner meal food eat restaurant"],
  ["🧹", "broom clean sweep chores"],
  ["🧺", "laundry basket chores"],
  ["🧼", "soap clean wash"],
  ["🛁", "bath bathtub clean"],
  ["🚿", "shower clean"],
  ["🧽", "sponge clean scrub"],
  ["🗑️", "trash garbage delete waste"],
  ["🔧", "wrench fix repair tool"],
  ["🔨", "hammer build repair tool"],
  ["🪛", "screwdriver fix tool"],
  ["⚙️", "gear settings machine"],
  ["🪚", "saw wood tool carpentry"],
  ["🪜", "ladder climb tool"],
  ["🔩", "bolt nut hardware"],
  ["🧰", "toolbox tools repair"],
  ["🔌", "plug electric power"],
  ["💡", "light bulb idea"],
  ["🔦", "flashlight torch light"],
  ["🕯️", "candle light"],
  ["🛒", "shopping cart groceries buy"],
  ["🛍️", "shopping bags buy retail"],
  ["👕", "shirt clothes clothing"],
  ["👗", "dress clothes clothing"],
  ["👖", "jeans pants clothes"],
  ["🧥", "coat jacket clothes"],
  ["👟", "sneaker shoe running"],
  ["👠", "heel shoe fashion"],
  ["🧢", "cap hat"],
  ["🎩", "top hat fancy"],
  ["👑", "crown king queen royal"],
  ["💄", "lipstick makeup beauty"],
  ["💅", "nails manicure beauty"],
  ["💇", "haircut salon hair"],
  ["🎵", "music note song"],
  ["🎶", "music notes song"],
  ["🎸", "guitar music instrument"],
  ["🎹", "piano music keyboard instrument"],
  ["🥁", "drums music instrument"],
  ["🎤", "microphone sing karaoke"],
  ["🎧", "headphones music listen"],
  ["🎬", "movie film clapper cinema"],
  ["🎥", "camera movie film video"],
  ["📷", "camera photo picture"],
  ["📺", "tv television show watch"],
  ["🎮", "game controller video gaming"],
  ["🕹️", "joystick game arcade"],
  ["🎲", "dice game board random"],
  ["♟️", "chess pawn game strategy"],
  ["🧩", "puzzle piece jigsaw"],
  ["🃏", "cards joker game"],
  ["🎨", "art palette paint creative"],
  ["🖌️", "paintbrush art paint"],
  ["🖍️", "crayon draw color"],
  ["🧵", "thread sewing craft"],
  ["🧶", "yarn knitting craft"],
  ["🏆", "trophy win award champion"],
  ["🥇", "gold medal first winner"],
  ["🥈", "silver medal second"],
  ["🥉", "bronze medal third"],
  ["🎖️", "medal military award"],
  ["🎓", "graduation cap school degree diploma"],
  ["🔑", "key lock unlock"],
  ["🔒", "lock secure private"],
  ["🔓", "unlock open"],
  ["🛡️", "shield protect security"],
  ["⚔️", "swords battle fight"],
  ["🏹", "bow arrow archery"],
  ["🧭", "compass navigation direction"],
  ["⌚", "watch time wrist"],
  ["⏱️", "stopwatch timer time"],
  ["🔔", "bell notification alert reminder"],
  ["🔕", "bell mute silence"],
  ["📢", "megaphone announce loud"],
  ["💬", "speech bubble chat message talk"],
  ["💭", "thought bubble think"],
  ["🗨️", "speech chat message"],
  ["❓", "question mark help"],
  ["❗", "exclamation important alert"],
  ["⚠️", "warning caution alert"],
  ["🚫", "no forbidden stop prohibited"],
  ["♻️", "recycle green environment"],
  ["🔄", "refresh repeat cycle sync"],
  ["➕", "plus add new"],
  ["➖", "minus subtract remove"],
  ["💯", "hundred perfect score"],
  ["🔟", "ten number"],
  ["🅰️", "letter a"],
  ["🅱️", "letter b"],
  ["🆗", "ok okay"],
  ["🆕", "new"],
  ["🆙", "up level"],
];
